### ISSUE TITLE
DF20-MINI download

### ISSUE THREAD

**Issue by bestswt** [picekl/DanishFungiDataset#1]
I only find the DF20 dataset, but can't find DF20-MINI

**Comment by picekl** [comment]
Hi,

The DF20-Mini is a subpart of the DF20. So you have to download the whole dataset and use the CSV metadata file to filter relevant images. Let me know if it helps.

Best,
Lukas

**Comment by sulc** [comment]
Hi bestswt,

thanks for your feedback. I am adding this to our TODO list - making a separate, smaller, archive with DF20-mini totally makes sense.
In the meantime, please feel free to use the filtering procedure from picekl's answer.

Have a nice day!

**Comment by bestswt** [comment]
thank

**Comment by picekl** [comment]
@bestswt Done! For the dataset download please refer to the dataset web.
