### ISSUE TITLE
some problem about the datasets

### ISSUE THREAD

**Issue by Xrazy** [picekl/DanishFungiDataset#2]
Hi, @picekl 
I am interest with FungiDataset and the competition held on Kaggle. I have some doubts with them.

1.  What is the difference between [Dev Images][~110Gb] and [Dev Images (max side size 300px)][~6.5Gb], which is the one you used to achieve your results?  I would like to choose smaller data to save my storage.
2. It seems there is only "scientificName" column which indicates the 1604 classes, so how can we submit "ClassId" for Kaggle competition?

**Comment by picekl** [comment]
Hi @Xrazy , Very good questions!

1. Dev [110Gb] contains original images in the original resolution (mostly 12MP). Dev [6.5] includes resized images, where max dimension is just 300px. There is no resized test set so be aware that resize might introduce some bias.
2. Fixed now. You can find the updated CSVs on Kaggle and the dataset web. The class_id that corresponds to scientificName was added.

Please do not hesitate to contact me if anything else occurs :)

Lukas
