### ISSUE TITLE
ClassId DF20-mini

### ISSUE THREAD

**Issue by Azatiussss** [picekl/DanishFungiDataset#3]
Hi, @picekl!
Could you please provide mapping from scientificName to ClassId on DF20-mini dataset? It seems that metadata provided doesn't have 'ClassId' column. Thank you in advance!

**Comment by picekl** [comment]
Hi @Azatiussss,

You should be able to make the class ids yourself relatively easily. There is no need to have "official mapping".

Or is there anything else behind that question? :)

Best,
Lukas

**Comment by Azatiussss** [comment]
Well, surely I am able to do that:) I meant the mapping your models were trained on. Is there anything special, or it is just LabelEncoder from sklearn for instance?
