### ISSUE TITLE
Are you from the future? Or is it just a typo 🤣

### ISSUE THREAD

**Issue by dylanjcastillo** [picekl/DanishFungiDataset#7]
Hey,

Thanks a lot for your work. Just noticed a small typo in the dates in the news section of the readme.

It says "20024" instead of "2024" :) 

Just wanted to let you know!

Best,
Dylan

**Comment by picekl** [comment]
Hi @dylanjcastillo,

Fixed from the past!
Thank you for pointing this out :) 

Best,
Lukas
